IF EXISTS (SELECT name FROM sysobjects WHERE name = 'sp_GetLastDateMonth' AND type = 'P')
	DROP PROCEDURE sp_GetLastDateMonth
GO
CREATE PROCEDURE sp_GetLastDateMonth
AS
BEGIN
	DECLARE @strMONTH CHAR(2),@strDATE AS CHAR(8)
	SET @strMONTH = RIGHT('0000' + CONVERT(VARCHAR(2),MONTH(GETDATE())),2)
	SET @strDATE = CONVERT(CHAR(4),YEAR(GETDATE())) + @strMONTH + '01'

	SELECT 
		CAST (@strDATE AS SMALLDATETIME) AS DATE_BEGIN,
		DATEADD(M,1, CAST (@strDATE AS SMALLDATETIME)) AS DATE_NEXT,
		DATEADD(D,-1,DATEADD(M,1, CAST (@strDATE AS SMALLDATETIME))) AS DATE_END
END